project:
  type: website

website:
  title: "Andrew Wray"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Research
        href: research.qmd
      - icon: github
        href: https://github.com/awray3
format:
  html:
    theme: slate
    highlight-style: dracula
    linkcolor: "#3b8bba"
    monofont: CaskaydiaCove Nerd Font
    css: styles.css



