project:
  type: website

website:
  title: "Andrew Wray"
  site-url: https://awray3.github.io
  favicon: static/img/favicon.ico
  description: Personal website and blog of Andrew Wray
  open-graph: 
    site-name: "Andrew Wray's Blog"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Research
        href: research.qmd
      - icon: github
        href: https://github.com/awray3
      - icon: mastodon
        href: https://fosstodon.org/@awray
      - icon: rss
        href: blog.xml
format:
  html:
    theme: 
      - slate
      - static/css/dark.scss
    monofont: CaskaydiaCove Nerd Font
    toc: true
    toc-location: right
    smooth-scroll: true
    email-obfuscation: javascript
    fig-cap-location: margin
    tbl-cap-location: margin
    # comments:
    #   utterances: 
    #     repo: awray3/blog-comments
    #     theme: preferred-color-scheme
    title-block-banner: false
    highlight-style: atom-one-dark
