[workspace]
authors = ["Andrew Wray <andrewwray2718@gmail.com>"]
channels = ["conda-forge"]
name = "attention"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
ipykernel = ">=6.29.5,<7"
pyyaml = ">=6.0.2,<7"
nbformat = ">=5.10.4,<6"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
pyx = ">=0.16, <0.17"
